/*
 * This file is generated by jOOQ.
 */
package com.horaoen.example4j.jooq.database;


import com.horaoen.example4j.jooq.database.tables.Author;
import com.horaoen.example4j.jooq.database.tables.Book;


/**
 * Convenience access to all tables in library.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>library.author</code>.
     */
    public static final Author AUTHOR = Author.AUTHOR;

    /**
     * The table <code>library.book</code>.
     */
    public static final Book BOOK = Book.BOOK;
}
